# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_binary_packages:
  - ggplot2
  - magrittr
  - xml2
  - xslt
  - testthat
  - readxl
  - dplyr
  - knitr
  - tidyr
  - rvest
  - rmarkdown
  - covr
  - hms
  - clipr
  - readr
  - rstudioapi
  - kableextra
  - ps
  - ini
  - processx
  - desc
  - prettyunits
  - xopen
  - clisymbols
  - fs
  - gh
  - whisker
  - callr
  - git2r
  - memoise
  - pkgbuild
  - pkgload
  - rcmdcheck
  - remotes
  - sessioninfo
  - usethis

r_packages:


notifications:
  email:
    on_success: change
    on_failure: change


after_success:
  - Rscript -e 'library(covr); codecov()'
